### ISSUE TITLE
Docs describe invalid filter for Audit functionality

### ISSUE THREAD

**Issue by Takadimi** [lyft/clutch#1128]
**Description**

It looks like at one point Config filters were set and functional on the `clutch.service.audit` service itself and were removed? https://github.com/lyft/clutch/commit/91bfa4a6381c96e5055cdfe061f09d2b67fcec25#diff-037973d02534a9e92ba9793dbb13e9f9c740d4d0af1bbbd3a237422e4a01fbe5L46

**Expected Behavior**

Either the docs are updated to reflect that only sink based filters are acceptable, or the code is updated such that filters can be applied again at the top level of the audit service.

**Actual Behavior**

The only request filters I'm able to leverage currently are on the sinks themselves, like so:

```yaml
services:
  - name: clutch.service.audit.sink.logger
    typed_config:
      "@type": types.google.com/clutch.config.service.audit.v1.SinkConfig
      filter:
        denylist: true
        rules:
          - field: METHOD
            text: SomeRequest
```

The [docs](https://clutch.sh/docs/advanced/security-auditing#recommended-production-setup), however, give an example with this filter set, but in my attempts to leverage it it was never applied.

## Screenshot From [Docs](https://clutch.sh/docs/advanced/security-auditing#recommended-production-setup)
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/3394151/111221508-f66cdd00-85b0-11eb-8dfb-79ec8a432490.png">

**Version**
Latest commit (b5d8b0147bd34c3535157e8fd537f77d93a53228) from March 15th, 2021.

**Comment by Takadimi** [comment]
Happy to fork and help make whatever update would be most desirable, just figured I'd open the issue first and get feedback. Thanks!

**Comment by danielhochman** [comment]
Good catch! Sorry we haven't responded sooner, this issue slipped through the cracks somehow. We would welcome a fix for this in the docs.

I believe it should read:
```yaml
      sinks:
        - clutch.service.audit.sink.logger
```

Instead of:
```yaml
      sinks:
        - clutch.service.audit.sink.slack
```

Here's one of our internal test configs as an example
```yaml
  - name: clutch.service.audit.sink.logger
  - name: clutch.service.audit
    typed_config:
      "@type": types.google.com/clutch.config.service.audit.v1.Config
      in_memory: true
      sinks:
        - clutch.service.audit.sink.logger
      filter:
        denylist: true
        rules:
            - field: METHOD
              text: Healthcheck
```
