### ISSUE TITLE
core: implement PagerDuty service

### ISSUE THREAD

**Issue by dschaller** [lyft/clutch#15]
**Description**

Implement [PagerDuty](https://www.pagerduty.com/) integration within Clutch as a service component.

This will involve both backend and frontend work. An example use of the integration could be adding on-call information within workflows if relevant.

Complexity [S/M/L]: M

**Wireframes, Mockups, or Screenshots (if applicable)**
TODO

**Comment by jpeach** [comment]
Per @mikecutalo on Slack:

>  I created this proxy module (https://github.com/lyft/clutch/tree/main/backend/module/proxy), I still need to add some documentation but its pretty simple. A lightweight way to talk to an external service without needing to setup a service.
>
>We use it to call pagerduty API’s, here is an example config.

```yaml
modules:
  - name: clutch.module.proxy
    typed_config:
      "@type": type.google.com/clutch.config.module.proxy.v1.Config
      services:
        - name: pagerduty
          host: https://api.pagerduty.com/
          allowed_requests:
            - path: /incidents
              method: GET
            - path: /services
              method: GET
          headers:
            Accept: "application/vnd.pagerduty+json;version=2"
            Authorization: "Token token=${PAGERDUTY_TOKEN}"
            Content-Type: "application/json"
```
