### ISSUE TITLE
authn: authorization error 400: invalid_scope with google

### ISSUE THREAD

**Issue by micnncim** [lyft/clutch#946]
**Description**

Facing `authorization error 400: invalid_scope` with Google. I deployed Clutch to GKE using the following configuration:

```yaml
gateway:
  listener:
    tcp:
      address: 0.0.0.0
      port: 8080
      secure: false
  logger:
    level: INFO
  stats:
    flush_interval: 1s
  middleware:
    - name: clutch.middleware.stats
    - name: clutch.middleware.validate
    - name: clutch.middleware.authn
modules:
  # - ...
  - name: clutch.module.healthcheck
  - name: clutch.module.resolver
  - name: clutch.module.assets
  - name: clutch.module.authn
services:
  # - ...
  - name: clutch.service.authn
    typed_config:
      "@type": types.google.com/clutch.config.service.authn.v1.Config
      oidc:
        issuer: ${OIDC_ISSUER}
        client_id: ${OIDC_CLIENT_ID}
        client_secret: ${OIDC_CLIENT_SECRET}
        redirect_url: ${OIDC_REDIRECT_URL}
      session_secret: ${AUTHN_SESSION_SECRET}

```

**Expected Behavior**

Not facing the error.

**Actual Behavior**

Facing the following error.

![Screenshot 2021-01-27 at 9 55 16](https://user-images.githubusercontent.com/21333876/105941382-a2f60c80-60a0-11eb-971e-bdb54381dd05.png)

> Error 400: invalid_scope
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.email], invalid=[offline_access]}

**Version**

```
$ cat go.mod
// ...

require (
// ...
	github.com/lyft/clutch/backend v0.0.0-20210126232808-846ebcbc9672
)

```

**Other Context**
